spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/liveScoresApp?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  # Cloudinary Properties
  cloudinary:
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
    resources:
      static-locations: file:./src/main/resources/static/
      cache-period: 0
football:
  api:
    key: ${FOOTBALL_API_KEY}
    url: "https://api.football-data.org/v4/competitions/PL/"
    header: "X-Auth-Token"
openai:
  api:
    key: ${OPENAI_API_KEY}
    url: "https://api.openai.com/v1/chat/completions"
