spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://premierleaguescores-server.mysql.database.azure.com:3306/premierleaguescores-database?serverTimezone=UTC&sslmode=required"
    username: xdwumppzdg  # Имейл адреса за връзка с базата
    password: Rt_7811207542  # Новата парола за връзка с базата
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  cloudinary:
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
  thymeleaf:
    check-template-location: true
    cache: true
    prefix: classpath:/templates/
    resources:
      static-locations: classpath:/static/
      cache-period: 0
football:
  api:
    key: ${FOOTBALL_API_KEY}
    url: "https://api.football-data.org/v4/competitions/PL/"
    header: "X-Auth-Token"
openai:
  api:
    key: ${OPENAI_API_KEY}
    url: "https://api.openai.com/v1/chat/completions"

# Настройки за грешките
server:
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: true

# Ниво на логиране за по-подробни грешки
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

# За да позволим работа в разработка, ако има нужда от това
spring.profiles.active: dev

# Application Insights конфигурация за диагностика
azure:
  application-insights:
    instrumentation-key: YOUR_INSTRUMENTATION_KEY
